version: '2'

services:

  bibbox-seeddms:
    image: bibbox/seeddms:6.0.11
    container_name:  bibbox-seeddms
    links:
      - bibbox-seeddms-db:seeddms-db
    ports:
      - "8065:80"
    depends_on:
      - bibbox-seeddms-db
      - bibbox-seeddms-data
    volumes_from: 
      - bibbox-seeddms-data

  bibbox-seeddms-db:
    image: mariadb
    container_name: bibbox-seeddms-db
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=bibbox
      - MYSQL_DATABASE=seeddms
      - MYSQL_USER=seeddms
      - MYSQL_PASSWORD=seeddms4bibbox
    volumes_from: 
      - bibbox-seeddms-data
    depends_on:
      - bibbox-seeddms-data

  bibbox-seeddms-data:
    image: busybox
    container_name: bibbox-seeddms-data
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
      - ./data/var/www/html/seeddms60x/data:/var/www/html/seeddms60x/data
